import java.util.*;
public class Prob6 {
    

    // lottery game in which you have to generate three digit number 
    // program prompts user to enter three digit number 
    // if user enters the same number as generated by program then user wins
    // award is 10000
    // if all the digits in the user input match all the digit in program award is 3000
    // if one digit matches the user inpit and program award is 1000
    
    public static void main(String[] args) {
     Scanner sc = new Scanner(System.in);
        Random r = new Random();

        

        System.out.println("Enter a three digit number");
        int entered_n = sc.nextInt();
        
        int r_n = r.nextInt(1000);
        System.out.println("random number is " + r_n);

        if(entered_n>99 && entered_n<1000){
            int a1 = entered_n%10;
            int b1 = (entered_n/10)%10;
            int c1 = entered_n/100;

            int a2 = r_n%10;
            int b2 = (r_n/10)%10;
            int c2 = r_n/100;
          
        if(entered_n == r_n){
            System.out.println("You win 10000");
        }
        else if(a1 == a2 || b1 == b2 || c1 == c2){
            System.out.println("You win 1000");
        }
        else if(a1 == a2 && b1 == b2 && c1 == c2){
            System.out.println("You win 3000");
        }
        else{
            System.out.println("You lose");
        }
       
    }
    }
}
